site_name: "A02 Graph Methods &bull; UTA027: Artificial Intelligence"

watch:
- src

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: summary.md
- section-index
- git-revision-date-localized
- git-committers:
    repository: "tiet-uta027/a02"
- git-authors
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          summary: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # show_object_full_path: true
          show_root_full_path: true
          show_root_heading: true
          show_source: false

theme:
  name: material
  custom_dir: docs/assets/theme-overrides
  features:
    - navigation.footer
    - header.autohide
    - content.tabs.link
    - navigation.tracking
    - navigation.top
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: amber
    accent: orange
  logo: assets/tiet-logo.svg
  favicon: assets/favicon.png

repo_url: https://github.com/tiet-uta027/a02
repo_name: tiet-uta027/a02
copyright: "Copyright &copy; 2025 <a href='https://bvraghav.com/'>Raghav B. Venkataramaiyer</a> &lt;<code style='color:inherit; background:transparent'>bv.raghav</code>&gt;"
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/tiet-uta027/a02.git
    name: Git Repo for Assignment A02

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
- https://unpkg.com/katex@0/dist/katex.min.js
- javascript/arithmatex.js

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {which: generic}
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          arithmatex: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {which: generic}
  - pymdownx.tabbed:
      alternate_style: true
  - mkdocs-click
